apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sharing-service
spec:
  selector:
    matchLabels:
      app: data-sharing-service
  template:
    metadata:
      labels:
        app: data-sharing-service
    spec:
      containers:
      - name: data-sharing-service
        image: waggle/data-sharing-service:0.0.2
        envFrom:
        - configMapRef:
            name: waggle-config
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-server"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-service-account-secret
              key: USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-service-account-secret
              key: PASSWORD
        resources:
          limits:
            cpu: 200m
            memory: 20Mi
          requests:
            cpu: 100m
            memory: 10Mi

