# Runs one instance of jetson-exporter on every node (DaemonSet) and expose
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jetson-exporter
  labels:
    app.kubernetes.io/name: jetson-exporter
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jetson-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jetson-exporter
        app.kubernetes.io/version: 0.0.1
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"
        resource.gpu: "true"
      priorityClassName: wes-high-priority
      containers:
        - name: jetson-exporter
          image: waggle/jetson-exporter:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/jetson-exporter"]
          args:
            - --loadpath
            - /host/sys/devices/gpu.0/load
          env:
            - name: PORT
              value: "9101"
            - name: KUBENODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_URL
              value: http://wes-node-influxdb.default.svc.cluster.local:8086
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wes-node-influxdb-waggle-token
                  key: token
            - name: INFLUXDB_ORG
              value: waggle
            - name: INFLUXDB_BUCKET
              value: waggle
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 50Mi
          ports:
            - name: http
              containerPort: 9101
              hostPort: 9101
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
      volumes:
        - hostPath:
            path: /sys
          name: sys
